name: Release

on:
  push:
    branches:
      - master
    tags:
      - '*'        # Push events to v1.0, v1.1, and v1.9 tags

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Get dependencies
      run: |
        go mod tidy

    - name: Lint
      uses: golangci/golangci-lint-action@v1
      with:
        version: v1.27

    - name: Test
      run: go test -v .

    - name: Build
      run: go build -v .

    - name: Docker
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: glvr182/f2b-exporter
        tag_with_ref: true 
        add_git_labels: true